#include <pthread.h>
#include <stdint.h>
#include "cpu_rpc_prot.h"
#include "cpu-server-client-mgr.h"

// rpc shm helpers
#define RPC_SHM_SUCCESS 0x3B
#define RPC_SHM_FAILURE 0x2A
#define RPC_SHM_MAGIC_START 0xD6 // 1 byte at beginnning of each RPC message. First byte of shm must always be = 0xD6
#define RPC_SHM_MAGIC_END 0xC5
#define RPC_SHM_ARG_DATA_START 8
#define RPC_SHM_MAX_ARG_LENGTH 128 // consistent with cudageterrorstring on server.

// 1 + 7 + 8 + 8 + 8 = 32 bytes/arg
struct rpc_shm_arg {
    uint8_t arg_type;
    uint8_t __pad3[7];
    struct {
        uint64_t val;
        uint64_t d_off;
    } raw_info;
    uint64_t arg_data_len;
}__attribute__((packed));

// 16 bytes /response meta
// points to the result struct.
// results will have to be memcpied into
// shm
typedef struct rpc_shm_response {
    uint64_t sz; // set by server
    uint64_t offset; // read by client
}__attribute__((packed)) rpc_shm_response_t ;

// 1 + 1 + 1 + 4 + 1 + 4 + 1 + 3 + 32 *16 + 16 + 1 = 545 bytes.
typedef struct rpc_shm_header {
    uint8_t rpc_magic_start;
    volatile uint8_t poll_s; // (R:Server, W: Client) On write by client, client sets it to 1, server reads then resets to 0
    volatile uint8_t poll_c; // (R: Client, W: Server) On write by server, server sets it to 1, client reads then resets to 0
    uint32_t pid;
    volatile uint8_t rpc_status; // RPC_SUCCESS/FAILURE

    uint32_t rpc_cmd;
    uint8_t num_args;
    uint8_t __pad2[3];

    struct rpc_shm_arg rpc_args[16]; // max 16 rpc args allowed.

    volatile rpc_shm_response_t rpc_response_desc;
    uint8_t rpc_magic_end;
}__attribute__((packed)) rpc_shm_header_t;

void rpc_shm_svc_put_response_and_notify(rpc_shm_header_t *rpc_hdr); // copy rpc control header to shm, update poll bit
uint32_t rpc_shm_svc_get_cuda_cmd();

extern int got_request;

inline void clflush(volatile void *p)
{
    asm volatile ("clflush (%0)" :: "r"(p));
}

// RPC API
#define RPC_CHECKPOINT 0
#define RPC_DEINIT 1
#define RPC_PRINTMESSAGE 2
#define RPC_DLOPEN 3
#define RPC_REGISTER_FUNCTION 50
#define RPC_ELF_LOAD 51
#define RPC_ELF_UNLOAD 52
#define RPC_REGISTER_VAR 53
#define RPC_INIT 54
#define RPC_CKP_RESTORE 55

// CUDA Runtime API
#define CUDA_CHOOSE_DEVICE 101
#define CUDA_DEVICE_GET_ATTRIBUTE 102
#define CUDA_DEVICE_GET_BY_PCI_BUS_ID 103
#define CUDA_DEVICE_GET_CACHE_CONFIG 104
#define CUDA_DEVICE_GET_LIMIT 105
#define CUDA_DEVICE_GET_P2P_ATTRIBUTE 107
#define CUDA_DEVICE_GET_PCI_BUS_ID 108
#define CUDA_DEVICE_GET_SHARED_MEM_CONFIG 109
#define CUDA_DEVICE_GET_STREAM_PRIORITY_RANGE 110
#define CUDA_DEVICE_GET_TEXTURE_LMW 111
#define CUDA_DEVICE_RESET 112
#define CUDA_DEVICE_SET_CACHE_CONFIG 113
#define CUDA_DEVICE_SET_LIMIT 114
#define CUDA_DEVICE_SET_SHARED_MEM_CONFIG 115
#define CUDA_DEVICE_SYNCHRONIZE 116
#define CUDA_GET_DEVICE 117
#define CUDA_GET_DEVICE_COUNT 118
void rpc_shm_svc_cuda_get_device_count_1(volatile rpc_shm_header_t *rpc_hdr_svc, int_result *res, cricket_client *client);

#define CUDA_GET_DEVICE_FLAGS 119

#define CUDA_GET_DEVICE_PROPERTIES 120
void rpc_shm_svc_cuda_get_device_properties_1(volatile rpc_shm_header_t *rpc_hdr_svc, int_result *res, cricket_client *client);

#define CUDA_SET_DEVICE 126
#define CUDA_SET_DEVICE_FLAGS 127
#define CUDA_SET_VALID_DEVICES 128
#define CUDA_GET_ERROR_NAME 140
#define CUDA_GET_ERROR_STRING 141
#define CUDA_GET_LAST_ERROR 142
#define CUDA_PEEK_AT_LAST_ERROR 143
#define CUDA_CTX_RESET_PERSISTING_L2CACHE 250
#define CUDA_STREAM_COPY_ATTRIBUTES 254
#define CUDA_STREAM_CREATE 255
#define CUDA_STREAM_CREATE_WITH_FLAGS 256
#define CUDA_STREAM_CREATE_WITH_PRIORITY 257
#define CUDA_STREAM_DESTROY 258
#define CUDA_STREAM_GET_FLAGS 262
#define CUDA_STREAM_GET_PRIORITY 263
#define CUDA_STREAM_IS_CAPTURING 264
#define CUDA_STREAM_QUERY 265
#define CUDA_STREAM_SYNCHRONIZE 267
#define CUDA_STREAM_WAIT_EVENT 268
#define CUDA_THREAD_EXCHANGE_STREAM_CAPTURE_MODE 269
#define CUDA_EVENT_CREATE 280
#define CUDA_EVENT_CREATE_WITH_FLAGS 281
#define CUDA_EVENT_DESTROY 282
#define CUDA_EVENT_ELAPSED_TIME 283
#define CUDA_EVENT_QUERY 284
#define CUDA_EVENT_RECORD 285
#define CUDA_EVENT_RECORD_WITH_FLAGS 286
#define CUDA_EVENT_SYNCHRONIZE 287
#define CUDA_FUNC_GET_ATTRIBUTES 310
#define CUDA_FUNC_SET_ATTRIBUTES 311
#define CUDA_FUNC_SET_CACHE_CONFIG 312
#define CUDA_FUNC_SET_SHARED_MEM_CONFIG 313
#define CUDA_LAUNCH_COOPERATIVE_KERNEL 314
#define CUDA_LAUNCH_KERNEL 317
#define CUDA_OCCUPANCY_AVAILABLE_DSMPB 330
#define CUDA_OCCUPANCY_MAX_ACTIVE_BPM 331
#define CUDA_OCCUPANCY_MAX_ACTIVE_BPM_WITH_FLAGS 332
#define CUDA_ARRAY_GET_INFO 400
#define CUDA_ARRAY_GET_SPARSE_PROPERTIES 401
#define CUDA_FREE 402
#define CUDA_FREE_ARRAY 403
#define CUDA_FREE_HOST 404
#define CUDA_GET_SYMBOL_ADDRESS 407
#define CUDA_GET_SYMBOL_SIZE 408
#define CUDA_HOST_ALLOC 409
#define CUDA_HOST_ALLOC_REGSHM 477
#define CUDA_HOST_GET_DEVICE_POINTER 410
#define CUDA_HOST_GET_FLAGS 411
#define CUDA_MALLOC 414
#define CUDA_MALLOC_3D 415
#define CUDA_MALLOC_3D_ARRAY 416
#define CUDA_MALLOC_ARRAY 417
#define CUDA_MALLOC_PITCH 421
#define CUDA_MEM_ADVISE 422
#define CUDA_MEM_GET_INFO 423
#define CUDA_MEM_PREFETCH_ASYNC 424
#define CUDA_MEMCPY_IVSHMEM 439
#define CUDA_MEMCPY_HTOD 440
#define CUDA_MEMCPY_DTOH 441
#define CUDA_MEMCPY_SHM 442
#define CUDA_MEMCPY_DTOD 443
#define CUDA_MEMCPY_TO_SYMBOL 445
#define CUDA_MEMCPY_TO_SYMBOL_SHM 446
#define CUDA_MEMCPY_IB 447
#define CUDA_MEMCPY_MT_HTOD 449
#define CUDA_MEMCPY_MT_DTOH 450
#define CUDA_MEMCPY_MT_SYNC 451
#define CUDA_MEMSET 470
#define CUDA_MEMSET_2D 471
#define CUDA_MEMSET_2D_ASYNC 472
#define CUDA_MEMSET_3D 473
#define CUDA_MEMSET_3D_ASYNC 474
#define CUDA_MEMSET_ASYNC 475
#define CUDA_DEVICE_CAN_ACCESS_PEER 500
#define CUDA_DEVICE_DISABLE_PEER_ACCESS 501
#define CUDA_DEVICE_ENABLE_PEER_ACCESS 502
#define CUDA_DRIVER_GET_VERSION 510
#define CUDA_RUNTIME_GET_VERSION 511
#define CUDA_PROFILER_START 701
#define CUDA_PROFILER_STOP 702

// CUDA Driver API
#define RPC_CUDEVICEGETCOUNT 1002
#define RPC_CUINIT 1003
#define RPC_CUDRIVERGETVERSION 1004
#define RPC_CUDEVICEGET 1005
#define RPC_CUDEVICENAME 1006
#define RPC_CUDEVICETOTALMEM 1007
#define RPC_CUDEVICEGETATTRIBUTE 1008
#define RPC_CUDEVICEGETUUID 1009
#define RPC_CUCCTXGETCURRENT 1010
#define RPC_CUCCTXSETCURRENT 1011
#define RPC_CUDEVICEPRIMARYCTXRETAIN 1012
#define RPC_CUMODULEGETFUNCTION 1013
#define RPC_CUMEMALLOC 1015
#define RPC_CUCCTXGETDEVICE 1016
#define RPC_CUMEMCPYHTOD 1017
#define RPC_CULAUCHKERNEL 1018
#define RPC_CUMODULELOAD 1019
#define RPC_CUGETERRORSTRING 1020
#define RPC_CUMODULEUNLOAD 1021
#define RPC_CUDEVICEPRIMARYCTXGETSTATE 1022
#define RPC_CUDEVICEGETPROPERTIES 1023
#define RPC_CUDEVICECOMPUTECAPABILITY 1024
#define RPC_CUDEVICEGETP2PATTRIBUTE 1025
#define RPC_CUMODULELOADDATA 1026

// Hidden Driver API
#define RPC_HIDDEN_GET_DEVICE_CTX 1101
#define RPC_HIDDEN_GET_MODULE 1105
#define RPC_HIDDEN_1_1 1111
#define RPC_HIDDEN_1_3 1113
#define RPC_HIDDEN_1_5 1115
#define RPC_HIDDEN_2_1 1121
#define RPC_HIDDEN_3_0 1130
#define RPC_HIDDEN_3_2 1132

// CUSOLVER
#define RPC_CUSOLVERDNCREATE 2001
#define RPC_CUSOLVERDNSETSTREAM 2002
#define RPC_CUSOLVERDNDGETRF_BUFFERSIZE 2003
#define RPC_CUSOLVERDNDGETRF 2004
#define RPC_CUSOLVERDNDGETRS 2005
#define RPC_CUSOLVERDNDESTROY 2006

// CUBLAS
#define RPC_CUBLASCREATE 3001
#define RPC_CUBLASDGE MM 3002
#define RPC_CUBLASDESTROY 3003
#define RPC_CUBLASSGEMM 3004
#define RPC_CUBLASSGEMV 3005
#define RPC_CUBLASDGEMV 3006
#define RPC_CUBLASSGEMMEX 3007
#define RPC_CUBLASSETSTREAM 3008
#define RPC_CUBLASSETWORKSPACE 3009
#define RPC_CUBLASSETMATHMODE 3010

// NVML
#define RPC_NVMLDEVICEGETCOUNT_V2 4000
#define RPC_NVMLINITWITHFLAGS 4001
#define RPC_NVMLINIT_V2 4002
#define RPC_NVMLSHUTDOWN 4003

// CUDNN
#define RPC_CUDNNGETVERSION 5000
#define RPC_CUDNNGETMAXDEVICEVERSION 5001
#define RPC_CUDNNGETCUDARTVERSION 5002
#define RPC_CUDNNGETERRORSTRING 5003
#define RPC_CUDNNQUERYRUNTIMEERROR 5004
#define RPC_CUDNNGETPROPERTY 5005
#define RPC_CUDNNCREATE 5006
#define RPC_CUDNNDESTROY 5007
#define RPC_CUDNNSETSTREAM 5008
#define RPC_CUDNNGETSTREAM 5009
#define RPC_CUDNNCREATETENSORDESCRIPTOR 5010
#define RPC_CUDNNSETTENSOR4DDESCRIPTOR 5011
#define RPC_CUDNNSETTENSOR4DDESCRIPTOREX 5012
#define RPC_CUDNNGETTENSOR4DDESCRIPTOR 5013
#define RPC_CUDNNSETTENSORNDDESCRIPTOR 5014
#define RPC_CUDNNSETTENSORNDDESCRIPTOREX 5015
#define RPC_CUDNNGETTENSORNDDESCRIPTOR 5016
#define RPC_CUDNNGETTENSORSIZEINBYTES 5017
#define RPC_CUDNNDESTROYTENSORDESCRIPTOR 5018
#define RPC_CUDNNTRANSFORM TENSOR 5024
#define RPC_CUDNNADDTENSOR 5026
#define RPC_CUDNNCREATEFILTERDESCRIPTOR 5041
#define RPC_CUDNNSETFILTER4DDESCRIPTOR 5042
#define RPC_CUDNNGETFILTER4DDESCRIPTOR 5043
#define RPC_CUDNNSETFILTERNDDESCRIPTOR 5044
#define RPC_CUDNNGETFILTERNDDESCRIPTOR 5045
#define RPC_CUDNNGETFILTERSIZEINBYTES 5046
#define RPC_CUDNNTRANSFORMFILTER 5047
#define RPC_CUDNNDESTROYFILTERDESCRIPTOR 5048
#define RPC_CUDNNSOFTMAXFORWARD 5049
#define RPC_CUDNNCREATEPOOLINGDESCRIPTOR 5050
#define RPC_CUDNNSETPOOLING2DDESCRIPTOR 5051
#define RPC_CUDNNGETPOOLING2DDESCRIPTOR 5052
#define RPC_CUDNNSETPOOLINGNDDESCRIPTOR 5053
#define RPC_CUDNNGETPOOLINGNDDESCRIPTOR 5054
#define RPC_CUDNNGETPOOLINGNDFORWARDOUTPUTDIM 5055
#define RPC_CUDNNGETPOOLING2DFORWARDOUTPUTDIM 5056
#define RPC_CUDNNDESTROPOOLINGDESCRIPTOR 5057
#define RPC_CUDNNPOOLINGFORWARD 5058
#define RPC_CUDNNCREATEACTIVATIONDESCRIPTOR 5059
#define RPC_CUDNNSETACTIVATIONDESCRIPTOR 5060
#define RPC_CUDNNGETACTIVATIONDESCRIPTOR 5061
#define RPC_CUDNNSETACTIVATIONDESCRIPTORSWISHBETA 5062
#define RPC_CUDNNGETACTIVATIONDESCRIPTORSWISHBETA 5063
#define RPC_CUDNNDESTROYACTIVATIONDESCRIPTOR 5064
#define RPC_CUDNNACTIVATIONFORWARD 5065
#define RPC_CUDNNCREATELRNDESCRIPTOR 5066
#define RPC_CUDNNSETLRNDESCRIPTOR 5067
#define RPC_CUDNNGETLRNDESCRIPTOR 5068
#define RPC_CUDNNDESTROYLRNDESCRIPTOR 5069
#define RPC_CUDNNLRNCROSSCHANNELFORWARD 5070
#define RPC_CUDNNCREATECONVOLUTIONDESCRIPTOR 5301
#define RPC_CUDNNDESTROICONVOLUTIONDESCRIPTOR 5302
#define RPC_CUDNNGETCONVOLUTIONNDFORWARDOUTPUTDIM 5303
#define RPC_CUDNNSETCONVOLUTIONNDDESCRIPTOR 5304
#define RPC_CUDNNGETCONVOLUTIONFORWARDALGORITHM_V7 5305
#define RPC_CUDNNFINDCONVOLUTIONFORWARDALGORITHM 5306
#define RPC_CUDNNGETCONVOLUTIONFORWARDWORKSPACESIZE 5307
#define RPC_CUDNNCONVOLUTIONFORWARD 5308
#define RPC_CUDNNBACKENDCREATEDESCRIPTOR 5309
#define RPC_CUDNNBACKENDDESTROYDESCRIPTOR 5310
#define RPC_CUDNNBACKENDINITIALIZE 5311
#define RPC_CUDNNBACKENDFINALIZE 5312
#define RPC_CUDNNBACKENDSETATTRIBUTE 5313
#define RPC_CUDNNBACKENDGETATTRIBUTE 5314
#define RPC_CUDNNBACKENDEXECUTE 5315
#define RPC_CUDNNSETCONVOLUTIONGROUPCOUNT 5316
#define RPC_CUDNNSETCONVOLUTIONMATHTYPE 5317
#define RPC_CUBLASLTCREATE 5318
#define RPC_CUBLASLTMATMULDESCCREATE 5319
#define RPC_CUBLASLTMATMULALGOGETHEURISTIC 5320
#define RPC_CUBLASLTMATMULDESCSETATTRIBUTE 5321
#define RPC_CUBLASLTMATMULDESCDESTROY 5322
#define RPC_CUBLASLTMATRIXLAYOUTCREATE 5323
#define RPC_CUBLASLTMATMULPREFERENCECREATE 5324
#define RPC_CUBLASLTMATMULPREFERENCEDESTROY 5325
#define RPC_CUBLASLTMATRIXLAYOUTDESTROY 5326
#define RPC_CUBLASLTMATMUL 5327
#define RPC_CUBLASGETMATHMODE 5328
#define RPC_CUBLASGEMMSTRIDEDBATCHEDEX 5329
#define RPC_CUBLASGEMMEX 5330
#define RPC_CUBLASGEMMSTRIDEDBATCHED 5331