[vm-resource-db]
host = "localhost"
port = 27017 
user = "adminUser"
password = "securePassword"
dbname = "flyt"

[ports]
node = 12401
client = 12402

[virt-server-auto-deallocate]
enabled = false
grace-period = 60

[ipc]
mqueue-path = "/tmp/flyt-rmgr-queue"
frontend-socket = "/tmp/flyt-frontend-socket"

[migration]
ckp-path = "/mnt/flytckp"
