[resource-manager]
address = "10.129.27.234"
port = 12401

[virt-server]
program-path = "/home/armaan/Work/SYNERG/Puru_Flyt/flyt/bin/cricket-rpc-server"
thread-mode = 1

[ipc]
mqueue-path = "/tmp/flyt-servernode-queue"
